{% set name = "empack" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc924fe0aff764a6f04143aac688dee4b2174de2698e5dc18309c03e714619d3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typer
    - requests
    - emsdk
    - pyyaml
    - pydantic

test:
  imports:
    - empack
    - empack.file_packager
  commands:
    - empack --help

about:
  home: https://github.com/emscripten-forge/empack
  summary: CLI for packing a mamba environment with emsdk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/emscripten-forge/empack

extra:
  recipe-maintainers:
    - DerThorsten
    - wolfv
    - martinRenou
