{% set name = "empack" %}
{% set version = "5.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12c4e3410efb369e4e14efe437e88edd27fb9acfced20bd690280fedcec0cbd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - hatch
  run:
    - python >=3.6
    - typer
    - requests
    - appdirs
    - pyyaml
    - networkx

test:
  imports:
    - empack
  commands:
    - empack --help

about:
  home: https://github.com/emscripten-forge/empack
  summary: CLI for packing a mamba environment with emsdk
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/emscripten-forge/empack

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - wolfv
    - martinRenou
