{% set name = "empack" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1011e7dcefe47e0ff50761903a30d29a0ebb4dd1251d1a931953344466e8f4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typer
    - requests
    - pyyaml
    - pydantic

test:
  imports:
    - empack
    - empack.file_packager
  commands:
    - empack --help

about:
  home: https://github.com/emscripten-forge/empack
  summary: CLI for packing a mamba environment with emsdk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/emscripten-forge/empack

extra:
  recipe-maintainers:
    - DerThorsten
    - wolfv
    - martinRenou
