{% set name = "empack" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f1fa455e9a9b6183d4b167b7a459f6631e23cca18e0ae61ea9be16ba4a40b8e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - hatch
  run:
    - python >=3.6
    - typer
    - requests
    - appdirs
    - pyyaml
    - pydantic >=2,<3
    - networkx

test:
  imports:
    - empack
  commands:
    - empack --help

about:
  home: https://github.com/emscripten-forge/empack
  summary: CLI for packing a mamba environment with emsdk
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/emscripten-forge/empack

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - wolfv
    - martinRenou
