{% set name = "empack" %}
{% set version = "2.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f665ac996757cb878ac4aecfd392aabff1a122859497020e6805db78f5351e25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - typer
    - requests
    - appdirs
    - pyyaml
    - pydantic
    - networkx

test:
  imports:
    - empack
    - empack.file_packager
  commands:
    - empack --help

about:
  home: https://github.com/emscripten-forge/empack
  summary: CLI for packing a mamba environment with emsdk
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/emscripten-forge/empack

extra:
  recipe-maintainers:
    - JohanMabille
    - DerThorsten
    - wolfv
    - martinRenou
